Repository ashu96902/Hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#3 this is used to have to find the second element
  SecondMax element
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#4 Create Search_String_arr
  Search_String_arr
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#6 Create Gold mining problem
  Gold mining problem
Labels: Hacktoberfest 2022, HACKTOBERFEST-ACCEPTED

#5 Create Find largest subtree sum in a tree
  Find largest subtree sum in a tree
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#10 Create Golomb Sequence
  Golomb Sequence
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#9 Create Cutting a road
  Cutting a road
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#8 Create Binomial coefficient
  Binomial coefficient
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#7 Create Binarytree
  Binarytree
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#14 Create Tiling with Dominoes
  Tiling with Dominoes
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#13 Create Painting Fence Algorithm
  Painting Fence Algorithm
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#12 Create SubSet Sum
  SubSet Sum
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#11 Create Choice of Area
  Choice of Area
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#18 Create Compute ncr
  Compute ncr
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#17 Create Coin Change
  Coin Change
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#16 Create Assembly line scheduling
  Assembly line scheduling
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#15 Create Largest Divisible pairs subset
  Largest Divisible pairs subset
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#19 Create hacktober python
  hacktober python
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#20 Create hacktober square
  hacktober square
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#21 Create hacktober sum
  hacktober sum
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#22 Create area of quadrilateral
  area of quadrilateral
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#23 Create recursion.c
  recursion.c
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#30 Create Activity selection
  Activity selection
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#29 Create Implace merge two arrays
  Implace merge two arrays
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#28 Create Sort binary array
  Sort binary array
Labels: Hacktoberfest 2022, Hacktoberfest, HACKTOBERFEST-ACCEPTED
